extends RefCounted

func run(t) -> void:
	var runtime_script = load("res://scripts/engine/case_runtime.gd")
	t.truthy(runtime_script != null, "case runtime script must exist")
	if runtime_script == null:
		return
	var prologue_data: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://data/cases/prologue.json"))
	var prologue_runtime = runtime_script.new()
	prologue_runtime.setup(prologue_data)
	t.truthy(not prologue_runtime.is_node_authenticated("mirror17.deadletter.zero"), "hidden tutorial node is not authenticated before its knowledge gate")
	t.equal(prologue_runtime.open_file("mirror17.deadletter.zero", "/archive/LW_最后一次校对.zlog").get("code"), "file_missing", "hidden tutorial node cannot be read before discovery")
	prologue_runtime.submit_search("零时邮局 mirror17")
	t.truthy(prologue_runtime.get_visible_addresses().has("mirror17.deadletter.zero"), "resolving the search gate reveals the tutorial node")
	t.truthy(not prologue_runtime.is_node_authenticated("mirror17.deadletter.zero"), "revealing the tutorial node does not bypass its lock")
	t.truthy(prologue_runtime.probe("mirror17.deadletter.zero").get("ok"), "the prologue mirror exposes its fictional lock layers")
	t.truthy(prologue_runtime.start_crack("mirror17.deadletter.zero").get("ok"), "the prologue mirror starts a short crack tutorial")
	prologue_runtime.tick(8.0, true)
	t.truthy(prologue_runtime.is_node_authenticated("mirror17.deadletter.zero"), "completing the tutorial crack authenticates the mirror")
	prologue_runtime.free()
	var case_data = JSON.parse_string(FileAccess.get_file_as_string("res://tests/fixtures/minimal_case.json"))
	var runtime = runtime_script.new()
	runtime.setup(case_data)
	var resolved_events: Array[String] = []
	var auth_events: Array[String] = []
	var trace_events: Array[String] = []
	t.truthy(runtime.has_signal("gate_resolved"), "case runtime exposes normalized gate facts")
	t.truthy(runtime.has_signal("node_authenticated"), "case runtime exposes normalized authentication facts")
	t.truthy(runtime.has_signal("counter_trace_reduced"), "case runtime exposes normalized counter-trace facts")
	if runtime.has_signal("gate_resolved"):
		runtime.gate_resolved.connect(func(id): resolved_events.append(id))
	if runtime.has_signal("node_authenticated"):
		runtime.node_authenticated.connect(func(addr): auth_events.append(addr))
	if runtime.has_signal("counter_trace_reduced"):
		runtime.counter_trace_reduced.connect(func(target): trace_events.append(target))
	t.equal(runtime.get_visible_addresses(), ["local.test", "login.test"], "start nodes are visible")
	var blocked: Dictionary = runtime.start_crack("locked.test")
	t.equal(blocked.get("ok"), false, "undiscovered node cannot be cracked")
	var results: Array = runtime.submit_search("长明 网络 科技")
	t.truthy(results.size() >= 1, "search returns matching gate")
	t.equal(resolved_events, ["kg_search"], "a newly resolved search gate emits one normalized fact")
	runtime.submit_search("长明 网络 科技")
	t.equal(resolved_events, ["kg_search"], "repeating a resolved search does not duplicate its fact")
	t.truthy(runtime.get_visible_addresses().has("locked.test"), "search gate reveals locked node")
	t.equal(runtime.start_crack("locked.test").get("code"), "probe_required", "crack requires probe")
	t.truthy(runtime.probe("locked.test").get("ok"), "probe succeeds")
	t.truthy(runtime.start_crack("locked.test").get("ok"), "crack starts after probe")
	runtime.tick(1.0, true)
	var focused_trace: float = runtime.get_trace_progress()
	t.truthy(focused_trace > 0.0, "focused terminal advances counter-trace")
	runtime.tick(1.0, false)
	var unfocused_delta: float = runtime.get_trace_progress() - focused_trace
	t.truthy(unfocused_delta > 0.0 and unfocused_delta < focused_trace, "unfocused counter-trace advances at reduced rate")
	runtime.tick(2.0, true)
	t.truthy(runtime.is_node_authenticated("locked.test"), "deterministic crack completes")
	t.equal(auth_events, ["locked.test"], "first crack authentication emits one normalized fact")
	runtime.tick(0.1, true)
	t.equal(auth_events, ["locked.test"], "browsing an authenticated node does not duplicate its fact")
	var trace_after_crack: float = runtime.get_trace_progress()
	runtime.tick(1.0, true)
	t.truthy(runtime.get_trace_progress() > trace_after_crack, "counter-trace continues while browsing after crack")
	t.truthy(runtime.consume_counter_signals().size() >= 1, "trace thresholds expose counter-signal targets")
	var trace_before_reduction: float = runtime.get_trace_progress()
	t.truthy(runtime.counter_trace("relay.test").get("ok"), "a valid counter relay lowers trace pressure")
	t.truthy(runtime.get_trace_progress() < trace_before_reduction, "valid counter tracing produces a real reduction")
	t.equal(trace_events, ["relay.test"], "a real counter-trace reduction emits its target")
	runtime.counter_trace("missing-relay")
	t.equal(trace_events, ["relay.test"], "invalid counter tracing emits no progress fact")
	t.equal(runtime.login("login.test", "CM-041", "wrong").get("ok"), false, "wrong credentials fail")
	t.truthy(runtime.login("login.test", "CM-041", "202303changming").get("ok"), "accepted credentials log in")
	t.equal(auth_events, ["locked.test", "login.test"], "first credential authentication emits one normalized fact")
	t.equal(resolved_events, ["kg_search", "kg_login"], "credential acceptance emits its newly resolved gate")
	runtime.login("login.test", "CM-041", "202303changming")
	t.equal(auth_events, ["locked.test", "login.test"], "repeating accepted credentials does not duplicate authentication")
	t.equal(resolved_events, ["kg_search", "kg_login"], "repeating accepted credentials does not duplicate gate resolution")
	t.equal(runtime.read_file("local.test", "/readme.txt").get("content"), "这里写着长明。", "text file can be read")
	t.equal(runtime.open_file("local.test", "/readme.txt").get("content"), "这里写着长明。", "open_file exposes the fixed runtime interface")
	t.truthy(runtime.read_files.has("local.test:/readme.txt"), "opening a file records reading state")
	runtime.mark_site_read("site_fixture")
	t.truthy(runtime.visited_sites.has("site_fixture"), "site visits are tracked")
	runtime.pin_screenshot("关键帧", "user://screenshots/frame.png")
	t.equal(runtime.pinned_screenshots.size(), 1, "pinned screenshots are tracked by runtime")
	t.truthy(runtime.collect_evidence("local.test", "/proof.txt").get("ok"), "evidence can be collected")
	t.truthy(runtime.collected_evidence.has("ev_proof"), "evidence id is recorded")
	runtime.collect_evidence("locked.test", "/secret.txt")
	t.truthy(runtime.can_open_report(), "report unlocks when all cited evidence is collected")
	t.equal(runtime.consume_triggered_horror().size(), 1, "evidence triggers horror once")
	t.equal(runtime.consume_triggered_horror().size(), 0, "consumed horror event is idempotent")
	runtime.submit_report_answer("q1", 1)
	runtime.submit_report_answer("q2", 1)
	runtime.submit_report_answer("q2", 0)
	runtime.submit_report_answer("q3", 2)
	t.equal(runtime.get_report_grade(), "B", "first-answer accuracy below eighty percent grades B")
	runtime.advance_hint_time(400.0)
	var saved_state: Dictionary = runtime.to_save_data()
	for key in ["readFiles", "visitedSites", "hintElapsed", "hintLevels", "screenshots", "reportGrade"]:
		t.truthy(saved_state.has(key), "save state includes %s" % key)
	var restored_runtime = runtime_script.new()
	restored_runtime.setup(case_data)
	restored_runtime.apply_save_data(saved_state)
	t.equal(restored_runtime.read_files, runtime.read_files, "reading state survives save restore")
	t.equal(restored_runtime.visited_sites, runtime.visited_sites, "site visits survive save restore")
	t.equal(restored_runtime.pinned_screenshots, runtime.pinned_screenshots, "screenshots survive save restore")
	t.equal(restored_runtime.hint_levels, runtime.hint_levels, "hint levels survive save restore")
	restored_runtime.free()
	runtime.free()
	var locked_runtime = runtime_script.new()
	locked_runtime.setup(case_data)
	locked_runtime.submit_search("长明")
	locked_runtime.probe("locked.test")
	locked_runtime.start_crack("locked.test")
	locked_runtime.tick(10.0, true)
	t.equal(locked_runtime.intrusion_marks, 1, "trace reaching one hundred records an intrusion mark")
	t.equal(locked_runtime.start_crack("locked.test").get("code"), "node_locked", "traced node is locked temporarily")
	locked_runtime.tick(20.1, true)
	t.truthy(locked_runtime.start_crack("locked.test").get("ok"), "node can be retried after lockout")
	locked_runtime.free()
	var hint_runtime = runtime_script.new()
	hint_runtime.setup(case_data)
	hint_runtime.advance_hint_time(360.1)
	t.truthy(hint_runtime.consume_hints().size() >= 1, "stalled unresolved gates emit first-level hints")
	var content_case: Dictionary = case_data.duplicate(true)
	content_case["horrorEvents"].append({"id": "h_read", "level": "B", "trigger": {"type": "content_read_seconds", "target": "site:test", "threshold": 2.0}, "once": true, "variants": {"full": {"text": "read"}}})
	hint_runtime.setup(content_case)
	hint_runtime.advance_content_read("site:test", 2.1)
	t.equal(hint_runtime.consume_triggered_horror().size(), 1, "content reading duration triggers configured horror event")
	hint_runtime.free()
